#!/usr/bin/with-contenv /bin/ash
log() {
	printf "%s\n" "$@"|awk '{print strftime("%FT%T%z",systime()),"[INFO] consul:",$0}'
}
loge() {
	printf "%s\n" "$@"|awk '{print strftime("%FT%T%z",systime()),"[ERROR] consul:",$0}'
}
###################################################################################################
if [ -e /data/raft/raft.db ]; then
	log "Starting up Consul"
	unset CONSUL_ENCRYPT_TOKEN
	exec s6-setuidgid consul /bin/consul agent -config-dir=/etc/consul/ -dc="$CONSUL_DC_NAME" -retry-join="$CONSUL_BOOTSTRAP_HOST" -retry-join="$CONSUL_DNS_NAME"
else
	log "Starting up Consul for the first time, using CONSUL_ENCRYPT_TOKEN & BOOTSTRAP_HOST environment variables"
	if [ "$CONSUL_ENCRYPT_TOKEN" ]; then
		exec s6-setuidgid consul /bin/consul agent -config-dir=/etc/consul/ -dc="$CONSUL_DC_NAME" -retry-join="$CONSUL_DNS_NAME" -encrypt="$CONSUL_ENCRYPT_TOKEN"
	else
		loge "CONSUL_ENCRYPT_TOKEN not set, aborting"
		exit 1
	fi
fi